Error occured (but it was rescued)

Someone tried to access invalid or restricted #{@error[:record_type]} with id #{@error[:record_id]}
